include(FetchContent)
set(ORT_VERSION 1.23.2)
if(WIN32)
  set(ORT_PLATFORM win-x64)
  set(ORT_EXT zip)
  set(ORT_HASH 0b38df9af21834e41e73d602d90db5cb06dbd1ca618948b8f1d66d607ac9f3cd)
elseif(APPLE)
  set(ORT_PLATFORM osx-universal2)
  set(ORT_EXT tgz)
  set(ORT_HASH 49ae8e3a66ccb18d98ad3fe7f5906b6d7887df8a5edd40f49eb2b14e20885809)
else()
  set(ORT_PLATFORM linux-x64)
  set(ORT_EXT tgz)
  set(ORT_HASH 1fa4dcaef22f6f7d5cd81b28c2800414350c10116f5fdd46a2160082551c5f9b)
endif()
FetchContent_Declare(ort URL "https://github.com/microsoft/onnxruntime/releases/download/v${ORT_VERSION}/onnxruntime-${ORT_PLATFORM}-${ORT_VERSION}.${ORT_EXT}" URL_HASH "SHA256=${ORT_HASH}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_MakeAvailable(ort)
add_library(onnxruntime::onnxruntime SHARED IMPORTED GLOBAL)
set_target_properties(onnxruntime::onnxruntime PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${ort_SOURCE_DIR}/include")
if(WIN32)
  set_target_properties(onnxruntime::onnxruntime PROPERTIES IMPORTED_LOCATION "${ort_SOURCE_DIR}/lib/onnxruntime.dll" IMPORTED_IMPLIB "${ort_SOURCE_DIR}/lib/onnxruntime.lib")
  install(FILES "${ort_SOURCE_DIR}/lib/onnxruntime.dll" DESTINATION bin)
elseif(APPLE)
  set_target_properties(onnxruntime::onnxruntime PROPERTIES IMPORTED_LOCATION "${ort_SOURCE_DIR}/lib/libonnxruntime.dylib")
else()
  set_target_properties(onnxruntime::onnxruntime PROPERTIES IMPORTED_LOCATION "${ort_SOURCE_DIR}/lib/libonnxruntime.so")
endif()
install(FILES "${ort_SOURCE_DIR}/LICENSE" "${ort_SOURCE_DIR}/ThirdPartyNotices.txt" DESTINATION licenses/onnxruntime)
